#!/usr/bin/env python3
"""Regenerate project_knowledge/{DATA_CATALOG,DATA_DICTIONARY,SOURCES}.md and
project_knowledge/latest/{macro_latest.csv,macro_metadata.json} from the current
state of config/, metadata/, and data/unified/. This is the ONLY folder meant to
be synced into the Claude Project (see project_knowledge/README.md) -- run this
after update_all.py so what's staged for GitHub reflects the latest run.
"""
from __future__ import annotations

import csv
import json
import shutil
import sys
import yaml
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
PK = REPO_ROOT / "project_knowledge"


def load_indicators() -> list[dict]:
    return yaml.safe_load((REPO_ROOT / "config" / "indicators.yaml").read_text(encoding="utf-8"))["indicators"]


def load_sources() -> dict:
    return yaml.safe_load((REPO_ROOT / "config" / "sources.yaml").read_text(encoding="utf-8"))["agencies"]


def load_metadata(agency: str, indicator_id: str) -> dict | None:
    path = REPO_ROOT / "metadata" / agency / f"{indicator_id.lower()}.json"
    if not path.exists():
        return None
    return json.loads(path.read_text(encoding="utf-8"))


def indicator_status(ind: dict) -> str:
    meta = load_metadata(ind["agency"], ind["id"])
    return "connected" if meta else "not_connected"


def build_data_catalog(indicators: list[dict]) -> str:
    lines = [
        "# Data Catalog",
        "",
        "Auto-generated by scripts/build_project_knowledge.py from config/indicators.yaml "
        "and metadata/**/*.json — do not hand-edit, edit the source config instead.",
        "",
        "| ID | Name (RU) | Agency | Frequency | Status | Period covered |",
        "|---|---|---|---|---|---|",
    ]
    for ind in indicators:
        meta = load_metadata(ind["agency"], ind["id"])
        status = "connected" if meta else "not connected"
        period = f"{meta['period_start']} .. {meta['period_end']}" if meta else "-"
        lines.append(f"| {ind['id']} | {ind['name_ru']} | {ind['agency']} | {ind['frequency']} | {status} | {period} |")
    n_connected = sum(1 for ind in indicators if load_metadata(ind["agency"], ind["id"]))
    lines += ["", f"**{n_connected} / {len(indicators)} indicators connected** as of the latest pipeline run."]
    return "\n".join(lines) + "\n"


def build_data_dictionary(indicators: list[dict]) -> str:
    lines = ["# Data Dictionary", "",
             "Auto-generated by scripts/build_project_knowledge.py from metadata/**/*.json. "
             "Only indicators with a successful pipeline run appear here with full detail; "
             "the rest are listed at the bottom as not yet connected.", ""]
    connected, not_connected = [], []
    for ind in indicators:
        meta = load_metadata(ind["agency"], ind["id"])
        if meta:
            connected.append((ind, meta))
        else:
            not_connected.append(ind)

    for ind, meta in connected:
        lines += [
            f"## {ind['id']}",
            f"- Name: {ind['name_ru']} / {ind['name_en']}",
            f"- Source: {meta['source']}, {meta['source_url']}",
            f"- Dataset ID: {meta['dataset_id']}",
            f"- Unit: {meta['unit']}",
            f"- Frequency: {meta['frequency']}",
            f"- Period covered: {meta['period_start']} .. {meta['period_end']}",
            f"- Methodology: {meta['methodology']}",
            f"- Transformation: {meta['transformation']}",
            f"- Revision status: {meta['revision_status']}",
            f"- Last updated: {meta['last_update_date']}",
            "",
        ]

    if not_connected:
        lines += ["## Not yet connected", ""]
        for ind in not_connected:
            src = load_sources().get(ind["agency"], {})
            endpoints = src.get("endpoints", {}) or {}
            reason = endpoints.get(ind["id"], {}).get("status", "pending_research") if isinstance(endpoints, dict) else "pending_research"
            lines.append(f"- **{ind['id']}** ({ind['name_ru']}) — {reason}")
    return "\n".join(lines) + "\n"


def build_sources_md(sources: dict) -> str:
    lines = [
        "# Sources — status",
        "",
        "Auto-generated by scripts/build_project_knowledge.py from config/sources.yaml. "
        "Full research trail (verified URLs, response formats, access barriers) lives there; "
        "this is a short human-readable summary.",
        "",
        "| Agency | Name | Status | Access type | Protection |",
        "|---|---|---|---|---|",
    ]
    for key, info in sources.items():
        lines.append(f"| {key} | {info['name']} | {info['status']} | {info.get('access_type', '-')} | {info.get('protection', '-')} |")
    return "\n".join(lines) + "\n"


def load_source_issues() -> list[dict]:
    path = REPO_ROOT / "config" / "source_issues.yaml"
    return yaml.safe_load(path.read_text(encoding="utf-8"))["issues"] if path.exists() else []


def _processed_rows(variable: str) -> list[dict]:
    """The processed rows of a scalar indicator or an item-level dataset, whichever exists."""
    for path in [*(REPO_ROOT / "data" / "processed").glob(f"*/{variable.lower()}.csv")]:
        with path.open(encoding="utf-8") as f:
            return list(csv.DictReader(f))
    return []


def issue_status(issue: dict) -> str:
    """'still in the data' while every pinned observation holds its recorded value."""
    pinned = issue.get("observations") or []
    if not pinned:
        return "caveat"
    rows = _processed_rows(issue["variable"])
    for obs in pinned:
        match = [r for r in rows if r["date"] == obs["date"]
                 and r.get("item_code", obs.get("item")) == obs.get("item", r.get("item_code"))
                 and (r.get("region") or "national") == obs.get("region", "national")]
        if not match or abs(float(match[0]["value"]) - float(obs["value"])) > 1e-6 * max(1.0, abs(float(obs["value"]))):
            return "no longer in the data -- source corrected? remove the entry"
    return "still in the data"


def build_source_issues_section(issues: list[dict]) -> str:
    lines = [
        "",
        "## Known problems in the sources",
        "",
        "From config/source_issues.yaml (audit 2026-09-25). The values are what the official files say "
        "and are kept as published; exclude or dummy them in a model.",
        "",
        "| Variable | Dates | Kind | Status | What to do |",
        "|---|---|---|---|---|",
    ]
    for issue in issues:
        dates = ", ".join(sorted({o["date"] for o in issue.get("observations") or []})) or "-"
        variable = issue["variable"] + (" (+ " + ", ".join(issue["also"]) + ")" if issue.get("also") else "")
        lines.append(f"| {variable} | {dates} | {issue['kind']} | {issue_status(issue)} | {issue['advice']} |")
    return "\n".join(lines) + "\n"


def refresh_latest(indicators: list[dict]) -> None:
    wide_src = REPO_ROOT / "data" / "unified" / "macro_wide.csv"
    latest_dir = PK / "latest"
    latest_dir.mkdir(parents=True, exist_ok=True)
    if wide_src.exists():
        shutil.copyfile(wide_src, latest_dir / "macro_latest.csv")

    bundle = {}
    for ind in indicators:
        meta = load_metadata(ind["agency"], ind["id"])
        if meta:
            bundle[ind["id"]] = meta
    (latest_dir / "macro_metadata.json").write_text(
        json.dumps(bundle, indent=2, ensure_ascii=False), encoding="utf-8"
    )


def main() -> int:
    indicators = load_indicators()
    sources = load_sources()

    (PK / "DATA_CATALOG.md").write_text(build_data_catalog(indicators) + build_source_issues_section(load_source_issues()),
                                        encoding="utf-8")
    (PK / "DATA_DICTIONARY.md").write_text(build_data_dictionary(indicators), encoding="utf-8")
    (PK / "SOURCES.md").write_text(build_sources_md(sources), encoding="utf-8")
    refresh_latest(indicators)
    print("project_knowledge/ refreshed.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
