#!/usr/bin/env python3
"""Regenerate project_knowledge/{DATA_CATALOG,DATA_DICTIONARY,SOURCES}.md,
project_knowledge/latest/macro_latest.csv (one row per series: the latest values) and
project_knowledge/models/*.md (the model reports) from the current state of config/,
metadata/, data/unified/ and models/. Everything here is sized for the Claude
Project's context: full histories and full metadata stay in the repository. This is the ONLY folder meant to
be synced into the Claude Project (see project_knowledge/README.md) -- run this
after update_all.py so what's staged for GitHub reflects the latest run.
"""
from __future__ import annotations

import csv
import json
import sys
import yaml
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
PK = REPO_ROOT / "project_knowledge"


def load_indicators() -> list[dict]:
    return yaml.safe_load((REPO_ROOT / "config" / "indicators.yaml").read_text(encoding="utf-8"))["indicators"]


def load_sources() -> dict:
    return yaml.safe_load((REPO_ROOT / "config" / "sources.yaml").read_text(encoding="utf-8"))["agencies"]


def load_metadata(agency: str, indicator_id: str) -> dict | None:
    path = REPO_ROOT / "metadata" / agency / f"{indicator_id.lower()}.json"
    if not path.exists():
        return None
    return json.loads(path.read_text(encoding="utf-8"))


def indicator_status(ind: dict) -> str:
    meta = load_metadata(ind["agency"], ind["id"])
    return "connected" if meta else "not_connected"


def build_data_catalog(indicators: list[dict]) -> str:
    """Counts by agency and frequency, plus what is not connected. The per-series list (name,
    agency, frequency, unit, period, latest values) is latest/macro_latest.csv -- one list, not
    two copies of it in the Project's context."""
    connected = [i for i in indicators if load_metadata(i["agency"], i["id"])]
    missing = [i for i in indicators if not load_metadata(i["agency"], i["id"])]
    lines = [
        "# Data Catalog",
        "",
        "Auto-generated by scripts/build_project_knowledge.py from config/indicators.yaml "
        "and metadata/**/*.json — do not hand-edit, edit the source config instead. "
        "Every series, with its Russian name, unit, period and latest values, is one row of "
        "`latest/macro_latest.csv`; its methodology is in `DATA_DICTIONARY.md`.",
        "",
        f"**{len(connected)} / {len(indicators)} indicators connected** as of the latest pipeline run.",
        "",
        "| Agency | Series | annual | quarterly | monthly | daily/irregular |",
        "|---|---|---|---|---|---|",
    ]
    agencies: dict[str, dict[str, int]] = {}
    for i in connected:
        f = i["frequency"] if i["frequency"] in ("annual", "quarterly", "monthly") else "other"
        agencies.setdefault(i["agency"], {}).setdefault(f, 0)
        agencies[i["agency"]][f] += 1
    for ag, c in sorted(agencies.items(), key=lambda kv: -sum(kv[1].values())):
        lines.append(f"| {ag} | {sum(c.values())} | {c.get('annual', 0)} | {c.get('quarterly', 0)} | "
                     f"{c.get('monthly', 0)} | {c.get('other', 0)} |")
    dims = REPO_ROOT / "config" / "dims.yaml"
    if dims.exists():
        ds = yaml.safe_load(dims.read_text(encoding="utf-8"))["datasets"]
        lines += ["", f"Item-level datasets (by partner, sector, region, decile …): {len(ds)}, listed in "
                      "config/dims.yaml; data in data/unified/macro_dims_long.csv.gz (not synced here)."]
    if missing:
        lines += ["", "## Not connected", ""] + [f"- {i['id']} ({i['name_ru']})" for i in missing]
    return "\n".join(lines) + "\n"


def _short(text: str, limit: int = 180) -> str:
    """First sentence, at most `limit` characters, safe inside a Markdown table cell."""
    text = " ".join((text or "").split()).replace("|", "/")
    cut = text.find(". ")
    if 0 < cut < limit:
        text = text[:cut + 1]
    return text if len(text) <= limit else text[:limit - 1].rstrip() + "…"


def build_data_dictionary(indicators: list[dict]) -> str:
    """One table row per connected series: unit, frequency, period and the first sentence of
    the methodology. The full metadata (source URL, dataset id, whole methodology, revision
    status) stays in metadata/<agency>/<id>.json -- it does not fit the Project's context."""
    lines = ["# Data Dictionary", "",
             "Auto-generated by scripts/build_project_knowledge.py from metadata/**/*.json. "
             "Short form for the Claude Project: the full record of each series (source URL, dataset "
             "id, complete methodology, transformation, revision status) is metadata/<agency>/<id>.json "
             "in the GitHub repository. Names are in DATA_CATALOG.md; latest values in latest/macro_latest.csv.", ""]
    by_agency: dict[str, list] = {}
    not_connected = []
    for ind in indicators:
        meta = load_metadata(ind["agency"], ind["id"])
        if meta:
            by_agency.setdefault(ind["agency"], []).append((ind, meta))
        else:
            not_connected.append(ind)
    for agency, rows in by_agency.items():
        lines += [f"## {agency}", "", "| ID | Unit | Freq | Period | Methodology (first sentence) |", "|---|---|---|---|---|"]
        for ind, meta in rows:
            period = f"{str(meta.get('period_start', ''))[:7]}..{str(meta.get('period_end', ''))[:7]}"
            lines.append(f"| {ind['id']} | {meta.get('unit', '')} | {meta.get('frequency', '')} | {period} | "
                         f"{_short(meta.get('methodology', ''))} |")
        lines.append("")
    if not_connected:
        lines += ["## Not yet connected", ""]
        for ind in not_connected:
            src = load_sources().get(ind["agency"], {})
            endpoints = src.get("endpoints", {}) or {}
            reason = endpoints.get(ind["id"], {}).get("status", "pending_research") if isinstance(endpoints, dict) else "pending_research"
            lines.append(f"- **{ind['id']}** ({ind['name_ru']}) — {reason}")
    return "\n".join(lines) + "\n"


def build_sources_md(sources: dict) -> str:
    lines = [
        "# Sources — status",
        "",
        "Auto-generated by scripts/build_project_knowledge.py from config/sources.yaml. "
        "Full research trail (verified URLs, response formats, access barriers) lives there; "
        "this is a short human-readable summary.",
        "",
        "| Agency | Name | Status | Access type | Protection |",
        "|---|---|---|---|---|",
    ]
    for key, info in sources.items():
        lines.append(f"| {key} | {info['name']} | {info['status']} | {info.get('access_type', '-')} | {info.get('protection', '-')} |")
    return "\n".join(lines) + "\n"


def load_source_issues() -> list[dict]:
    path = REPO_ROOT / "config" / "source_issues.yaml"
    return yaml.safe_load(path.read_text(encoding="utf-8"))["issues"] if path.exists() else []


def _processed_rows(variable: str) -> list[dict]:
    """The processed rows of a scalar indicator or an item-level dataset, whichever exists."""
    for path in [*(REPO_ROOT / "data" / "processed").glob(f"*/{variable.lower()}.csv")]:
        with path.open(encoding="utf-8") as f:
            return list(csv.DictReader(f))
    return []


def issue_status(issue: dict) -> str:
    """'still in the data' while every pinned observation holds its recorded value."""
    pinned = issue.get("observations") or []
    if not pinned:
        return "caveat"
    rows = _processed_rows(issue["variable"])
    for obs in pinned:
        match = [r for r in rows if r["date"] == obs["date"]
                 and r.get("item_code", obs.get("item")) == obs.get("item", r.get("item_code"))
                 and (r.get("region") or "national") == obs.get("region", "national")]
        if not match or abs(float(match[0]["value"]) - float(obs["value"])) > 1e-6 * max(1.0, abs(float(obs["value"]))):
            return "no longer in the data -- source corrected? remove the entry"
    return "still in the data"


def build_source_issues_section(issues: list[dict]) -> str:
    lines = [
        "",
        "## Known problems in the sources",
        "",
        "From config/source_issues.yaml (audit 2026-09-25). The values are what the official files say "
        "and are kept as published; exclude or dummy them in a model.",
        "",
        "| Variable | Dates | Kind | Status | What to do |",
        "|---|---|---|---|---|",
    ]
    for issue in issues:
        dates = ", ".join(sorted({o["date"] for o in issue.get("observations") or []})) or "-"
        variable = issue["variable"] + (" (+ " + ", ".join(issue["also"]) + ")" if issue.get("also") else "")
        lines.append(f"| {variable} | {dates} | {issue['kind']} | {issue_status(issue)} | {issue['advice']} |")
    return "\n".join(lines) + "\n"


def latest_snapshot(indicators: list[dict]) -> list[dict]:
    """One row per series from data/unified/macro_long.csv: the last observation, the one
    before it and the value a year earlier. The full history is data/unified/ in the repo --
    a wide copy of it (5.5 MB, every series since 1947) was far beyond the Project's context."""
    path = REPO_ROOT / "data" / "unified" / "macro_long.csv"
    if not path.exists():
        return []
    series: dict[str, list[tuple[str, str]]] = {}
    info: dict[str, dict] = {}
    with path.open(encoding="utf-8") as f:
        for r in csv.DictReader(f):
            if (r.get("region") or "national") != "national" or r["value"] in ("", "nan"):
                continue
            series.setdefault(r["variable"], []).append((r["date"], r["value"]))
            info[r["variable"]] = r
    names = {i["id"]: i for i in indicators}
    rows = []
    for var in sorted(series):
        obs = sorted(series[var])
        last_date, last_value = obs[-1]
        prev_date, prev_value = obs[-2] if len(obs) > 1 else ("", "")
        year_ago = str(int(last_date[:4]) - 1) + last_date[4:]
        ago = dict(obs).get(year_ago, "")
        ind = names.get(var, {})
        rows.append({
            "id": var, "name_ru": ind.get("name_ru", ""), "agency": info[var].get("source", ""),
            "frequency": info[var].get("frequency", ""), "unit": info[var].get("unit", ""),
            "first_date": obs[0][0], "n_obs": len(obs), "last_date": last_date, "last_value": last_value,
            "prev_date": prev_date, "prev_value": prev_value, "year_ago_value": ago,
        })
    return rows


def refresh_latest(indicators: list[dict]) -> None:
    latest_dir = PK / "latest"
    latest_dir.mkdir(parents=True, exist_ok=True)
    rows = latest_snapshot(indicators)
    if rows:
        with (latest_dir / "macro_latest.csv").open("w", encoding="utf-8", newline="") as f:
            w = csv.DictWriter(f, fieldnames=list(rows[0]))
            w.writeheader()
            w.writerows(rows)
    # metadata now lives in DATA_DICTIONARY.md (short) and metadata/ (full); the 0.5 MB bundle is gone
    (latest_dir / "macro_metadata.json").unlink(missing_ok=True)


def refresh_models() -> None:
    """Copy each model's report (text only, no charts) so the Project sees current estimates."""
    out = PK / "models"
    reports = sorted((REPO_ROOT / "models").glob("*/REPORT.md"))
    if not reports:
        return
    out.mkdir(exist_ok=True)
    for rep in reports:
        text = "\n".join(line for line in rep.read_text(encoding="utf-8").splitlines()
                         if not line.startswith("!["))
        note = (f"<!-- Copied from models/{rep.parent.name}/REPORT.md by scripts/build_project_knowledge.py; "
                f"charts and CSVs are in that folder on GitHub. -->\n")
        (out / f"{rep.parent.name}.md").write_text(note + text, encoding="utf-8")


def main() -> int:
    indicators = load_indicators()
    sources = load_sources()

    (PK / "DATA_CATALOG.md").write_text(build_data_catalog(indicators) + build_source_issues_section(load_source_issues()),
                                        encoding="utf-8")
    (PK / "DATA_DICTIONARY.md").write_text(build_data_dictionary(indicators), encoding="utf-8")
    (PK / "SOURCES.md").write_text(build_sources_md(sources), encoding="utf-8")
    refresh_latest(indicators)
    refresh_models()
    print("project_knowledge/ refreshed.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
